[package]
name = "bitcask-repl"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcask-lib = { path = "../bitcask-lib" }
rand = "0.8.5"
